sonar.projectKey=smartOrder
sonar.projectName=SmartOrder
sonar.projectVersion=1.0

# Source + test
sonar.sources=frontend/src,backend/src
sonar.tests=frontend/tests,backend/tests
sonar.test.inclusions=frontend/tests/**/*.test.ts,frontend/tests/**/*.test.tsx,backend/tests/**/*.py

# Python coverage

sonar.python.version=3.14
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# External issues (requisiti)
sonar.externalIssuesReportPaths=req_issues.json

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude patterns (opzionale)
sonar.exclusions=**/__pycache__/**,**/venv/**,**/.pytest_cache/**
