name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
      - main
    paths:
      - backend/src/**
      - backend/tests/**

jobs:
  backend-tests:
    # needs: changes
    # if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4