name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/src/**'
              - 'frontend/tests/**'
            backend:
              - 'backend/src/**'
              - 'backend/tests/**'

  frontend-tests:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run test

  backend-tests:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # Attiva il caching automatico
          cache-dependency-path: 'backend/requirements.txt'
      - name: Installazione dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analisi statica
        run: mypy src

      - name: Analisi Dinamica (pytest)
        run: pytest
      
