name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/src/**'
              - 'frontend/tests/**'
            backend:
              - 'backend/src/**'
              - 'backend/tests/**'

  frontend-tests:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
    #   - run: |
    #      if [[ "${{ needs.changes.outputs.frontend }}" != "true" ]]; then
    #         echo "No frontend changes, skipping"
    #         exit 0
    #      fi
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run test

  backend-tests:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
    #   - run: |
    #       if [[ "${{ needs.changes.outputs.backend }}" != "true" ]]; then
    #         echo "No frontend changes, skipping"
    #         exit 0
    #       fi
  check-tests-passed:
    needs: [frontend-tests, backend-tests]
    if: always() # Viene eseguito anche se i test precedenti sono stati saltati
    runs-on: ubuntu-latest
    steps:
      - name: Verify test results
        run: |
          # Verifica che nessuno dei test necessari sia fallito
          stringa_errore=""
          # In Bash la concatenazione si fa accostando le variabili, senza il +
          if [[ "${{ needs.frontend-tests.result }}" == "failure" ]]; then
            stringa_errore="${stringa_errore} [Frontend fallito]"
          fi
          
          if [[ "${{ needs.backend-tests.result }}" == "failure" ]]; then
            stringa_errore="${stringa_errore} [Backend fallito]"
          fi

          # Gli spazi dentro le parentesi [[ ]] sono OBBLIGATORI
          if [[ -z "$stringa_errore" ]]; then
            echo "Tutti i test rilevanti sono passati o sono stati saltati correttamente."
            exit 0
          else
            echo "ERRORE CI: $stringa_errore"
            exit 1
          fi

