name: Crea PR da feature a develop

on:
  push:
    branches:
      - feature/*

permissions:
  pull-requests: write
  contents: read

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pull Request Automatica - ${{ github.ref_name }} → develop"
          pr_body: "PR automatica generata dal push su ${{ github.ref_name }}"